
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.network "forwarded_port", guest: 80, host: 8020

  config.vm.network "private_network", ip: "192.168.33.20"
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
    vb.customize [
      "modifyvm", :id,
      "--vram", "256",
      "--clipboard", "bidirectional",
      "--draganddrop", "bidirectional",
    ]
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y ubuntu-desktop
  SHELL
end
